project_id = "lnokphjzmvdegutjpxhw"

[functions.email-domain-status]
verify_jwt = false

[functions.wallet-usage-processor]
verify_jwt = false

[functions.withdrawal-request]
verify_jwt = false

[functions.scan-wallet-transactions]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.transaction-notification-processor]
verify_jwt = false

[functions.debug-wallet-addresses]
verify_jwt = false

[functions.fix-all-wallet-addresses]
verify_jwt = false

[functions.repair-wallet-emails]
verify_jwt = false

[functions.sync-wallet-emails]
verify_jwt = false

[functions.telegram-bot-handler]
verify_jwt = false

[functions.execute-transfer]
verify_jwt = false

[functions.transfer-config]
verify_jwt = false

[functions.monitor-wallet-transfers]
verify_jwt = false