project_id = "lnokphjzmvdegutjpxhw"

[functions.manual-wallet-scan]
verify_jwt = false

[functions.force-wallet-rescan]
verify_jwt = false

[functions.email-domain-status]
verify_jwt = false

[functions.wallet-usage-processor]
verify_jwt = false

[functions.withdrawal-request]
verify_jwt = false

[functions.scan-wallet-transactions]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.transaction-notification-processor]
verify_jwt = false

[functions.debug-wallet-addresses]
verify_jwt = false

[functions.fix-all-wallet-addresses]
verify_jwt = false

[functions.repair-wallet-emails]
verify_jwt = false

[functions.sync-wallet-emails]
verify_jwt = false

[functions.telegram-bot-handler]
verify_jwt = false

[functions.execute-transfer]
verify_jwt = false

[functions.transfer-config]
verify_jwt = false

[functions.monitor-wallet-transfers]
verify_jwt = false

[functions.get-wallet]
verify_jwt = false

[functions.monitor-generated-wallet]
verify_jwt = false

[functions.cleanup-old-wallets]
verify_jwt = false

[functions.schedule-wallet-scans]
verify_jwt = false

[functions.process-scheduled-scans]
verify_jwt = false