project_id = "lnokphjzmvdegutjpxhw"

[functions.wallet-usage-processor]
verify_jwt = false

[functions.withdrawal-request]
verify_jwt = false

[functions.scan-wallet-transactions]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.transaction-notification-processor]
verify_jwt = false

[functions.debug-wallet-addresses]
verify_jwt = false

[functions.fix-all-wallet-addresses]
verify_jwt = false