project_id = "lnokphjzmvdegutjpxhw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54324

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.send-marketing-email]
verify_jwt = false

[functions.send-marketing-sms]
verify_jwt = false

[functions.track-email-open]
verify_jwt = false

[functions.check-balance]
verify_jwt = false

[functions.webrtc-calling]
verify_jwt = false

[functions.auto-balance-trigger]
verify_jwt = false

[functions.backfill-commercial-names]
verify_jwt = false

[functions.handle-email-bounce]
verify_jwt = false

[functions.webrtc-sip-gateway]
verify_jwt = false

[edge-runtime]
inspector_port = 8083
policy = "per_worker"
worker_count = 1