// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnokphjzmvdegutjpxhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxub2twaGp6bXZkZWd1dGpweGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MDEzNzEsImV4cCI6MjA2NDQ3NzM3MX0.0YfR0lypCmnt2dZUKp4b2jk8n0EIs4R9RUq5NvOcu1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});